# Case study cricket

#### **Players are Sachin, Rahul, India**

* <font color = 'Green'>*Each row depicts matches*</font> 
* <font color = 'Green'>*Each column depicts the scores of the respective players*</font>  


### **Gather**

In [ ]:
import numpy as np
import pandas as pd


### Problem Questions

1.   <font color = 'Green'>**Find mean, median, IQR for Sachin, Rahul, and India** 
2.   <font color = 'Green'>**Find the histogram of Sachin's scores with 10 bins**
3.   <font color = 'Green'>**Find mean of Sachin's scores grouped by 25 matches**
4.   <font color = 'Green'>**Find mean of Sachin's scores where he has scored a century**
5.   <font color = 'Green'>**Find mean of Sachin's scores when Rahul has scored less than 10**
6.   <font color = 'Green'>**Find mean for Sachin's scores based on which quartile India's score falls** 
7.   <font color = 'Green'>**For every match find out who has has scored more - Sachin or Rahul**
8.   <font color = 'Green'>**How many matches did Sachin take to score first 1000 runs, next 1000 runs, ...**



### **Assess**

In [ ]:
scores = np.loadtxt('cric_data.tsv', skiprows = 1, usecols = [1,2,3])

In [ ]:
scores

array([[100.,  78., 342.],
       [ 11.,  62., 191.],
       [  8.,  85., 252.],
       [ 71.,  24., 307.],
       [104.,  17., 229.],
       [ 18., 104., 246.],
       [  8.,  76., 226.],
       [ 86.,  74., 288.],
       [ 12.,  60., 216.],
       [ 85.,  12., 224.],
       [ 18.,  63., 161.],
       [  4., 107., 276.],
       [  7.,  76., 283.],
       [ 37.,   4., 297.],
       [ 14.,   5., 139.],
       [  0.,  33., 224.],
       [  4.,   7., 178.],
       [  0.,   0.,   0.],
       [ 21.,  36., 193.],
       [  1.,  66., 231.],
       [ 62.,   0., 134.],
       [  0., 123., 246.],
       [138.,  39., 299.],
       [ 38.,   9., 242.],
       [  2.,  11., 214.],
       [ 46.,  14., 152.],
       [ 65.,   0., 104.],
       [  0.,   0.,   4.],
       [ 39.,  26., 155.],
       [ 48.,   4., 168.],
       [141.,  48., 282.],
       [ 62.,   7., 228.],
       [ 12.,  73., 231.],
       [  1.,  86., 238.],
       [ 41.,  32., 255.],
       [ 11.,  82., 273.],
       [  3.,  25., 143.],
 

### **Problem 1**   
<font color = 'Green'>**Find mean, median, IQR for Sachin, Rahul, and India** 

In [ ]:
sachin = scores[:, 0]
rahul = scores[:, 1]
india = scores[:, 2]

In [ ]:
def stats(col):
    print('mean: ', np.mean(col))
    print('median: ', np.median(col))
    print('IQR: ', np.percentile(col, 75) - np.percentile(col, 25))

In [ ]:
stats(sachin)

mean:  39.87555555555556
median:  27.0
IQR:  57.0


In [ ]:
stats(rahul)

mean:  32.062222222222225
median:  22.0
IQR:  46.0


In [ ]:
stats(india)

mean:  220.79555555555555
median:  216.0
IQR:  98.0


### **Problem 2**       
<font color = 'Green'>**Find the histogram of Sachin's scores with 10 bins**


In [ ]:
sachin_histogram = np.histogram(s, bins = 10)

In [ ]:
sachin_histogram

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1], dtype=int32),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

### **Problem 3**
<font color = 'Green'>**Find mean of Sachin's scores grouped by 25 matches**

In [ ]:
sachin.shape

(225,)

In [ ]:
sachin.reshape(9, 25)

array([[100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  85.,  18.,
          4.,   7.,  37.,  14.,   0.,   4.,   0.,  21.,   1.,  62.,   0.,
        138.,  38.,   2.],
       [ 46.,  65.,   0.,  39.,  48., 141.,  62.,  12.,   1.,  41.,  11.,
          3., 186.,  11.,  27.,  27.,  51.,  18.,  32., 146.,   5.,  45.,
        141.,  12.,  65.],
       [ 27.,   7.,  16.,   2.,  28.,   6., 123., 120.,   7.,   3.,   0.,
         81.,   2.,  54., 122.,   4.,  14.,   0., 100.,  15.,   0.,  57.,
         99.,  37.,  38.],
       [ 32.,  21.,  32.,  40.,   0.,   5.,   8.,   5.,   0.,  50.,  30.,
         37.,  89.,   4.,  98.,  83.,  93.,   0.,  52., 152.,   1.,   8.,
         93.,  45.,  26.],
       [  0.,   1.,   0.,  16.,  47.,  89.,   3.,   1.,  53.,  16.,   0.,
         81.,  14.,  78.,   6., 105., 122.,   9.,   8.,  28.,  35.,  69.,
         13.,  97.,  93.],
       [  2.,  36.,  39.,   2.,  29.,  12.,  19.,  34.,   2., 100.,  44.,
         82.,   0.,  79.,   6.,   9.,   8.,  23.,  

In [ ]:
np.mean(sachin.reshape(9, 25), axis = 1)

array([33.96, 49.4 , 38.48, 40.16, 39.36, 38.2 , 44.6 , 39.52, 35.2 ])

### **Problem 4**
<font color = 'Green'>**Find mean of Sachin's scores where he has scored a century**


In [ ]:
sachin[sachin>=100]

array([100., 104., 138., 141., 186., 146., 141., 123., 120., 122., 100.,
       152., 105., 122., 100., 117., 141., 139., 114., 127., 110., 146.,
       101., 140., 113., 102.])

In [ ]:
np.mean(sachin[sachin >= 100])

125.0

### **Problem 5**
<font color = 'Green'>**Find mean of Sachin's scores when Rahul has scored less than 10**

In [ ]:
sachin[rahul <= 10]

array([ 37.,  14.,   4.,   0.,  62.,  38.,  65.,   0.,  48.,  62.,  27.,
        27.,  51.,  18.,  65.,  28.,   2.,  54.,   4.,  14., 100.,  57.,
         0.,   5.,   0.,  30.,  83.,  93.,   0., 152.,   0.,   1.,  53.,
         0.,  81.,  78., 122.,   9.,  13.,  36.,  29.,  12.,  34., 100.,
        44.,  82.,   0.,   6.,  49.,  64.,  43.,  72.,   3.,  44.,  47.,
        17.,  35.,  88.,   0.,  33., 110., 146.,   7.,  11.,  94.,  55.,
         0.,  28.,   2.,  27.,  40.])

In [ ]:
np.mean(sachin[rahul <= 10])

40.2112676056338

## **Problem 6**
<font color = 'Green'>**Find mean for Sachin's scores based on which quartile India's score falls** 


In [ ]:
india_quartile = np.percentile(india, [25,50,75,100])

In [ ]:
india_quartile = india_quartile.reshape(4,1)

In [ ]:
indices = india < india_quartile

In [ ]:
sachin[indices[1, :]]

array([ 11.,  18.,  14.,   4.,   0.,  21.,  62.,   2.,  46.,  65.,   0.,
        39.,  48.,   3.,  11.,   5.,  65.,  27.,   7.,   2.,  28.,   6.,
         7.,   3.,   2.,   4., 100.,  15.,  32.,  40.,   0.,   5.,   8.,
         5.,   0.,  30.,  37.,  89.,   0.,  52.,  93.,  45.,   0.,   1.,
         0.,   3.,   0.,  81.,  78.,   6.,  28.,  13.,  93.,   2.,  36.,
         2.,  12.,  19.,  34.,   2.,  82.,   0.,   6.,   8.,  23.,  35.,
        74., 117.,  49.,  64.,   5.,  17.,   0.,  44.,  68.,   3.,  47.,
        17.,  35.,  88., 127.,   0.,  45.,  33., 110.,   7.,  25.,   9.,
         2.,  11.,  17.,   1.,  45.,   9.,  67.,  10.,  55.,   0.,   1.,
       101.,  23.,   1.,  41.,   1.,  28.,   2.,  22.,  25.,   0.,  27.,
        40.])

In [ ]:
for i in range(4):
    print(i, np.mean(sachin[indices[i]]))

0 19.672727272727272
1 28.18018018018018
2 31.688622754491018
3 39.799107142857146


## **Problem 7**
<font color = 'Green'>**For every match find out who has has scored more - Sachin or Rahul**

In [ ]:
scores_of_sachin_and_rahul = scores[:, 0:2]

In [ ]:
is_rahul_higher = np.argmax(scores_of_sachin_and_rahul, axis = 1)

In [ ]:
is_rahul_higher

array([0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0], dtype=int32)

In [ ]:
highest_scored_player = np.where(is_rahul_higher == 0, 'sachin', 'rahul')

In [ ]:
highest_scored_player

array(['sachin', 'rahul', 'rahul', 'sachin', 'sachin', 'rahul', 'rahul',
       'sachin', 'rahul', 'sachin', 'rahul', 'rahul', 'rahul', 'sachin',
       'sachin', 'rahul', 'rahul', 'sachin', 'rahul', 'rahul', 'sachin',
       'rahul', 'sachin', 'sachin', 'rahul', 'sachin', 'sachin', 'sachin',
       'sachin', 'sachin', 'sachin', 'sachin', 'rahul', 'rahul', 'sachin',
       'rahul', 'rahul', 'sachin', 'rahul', 'sachin', 'sachin', 'sachin',
       'sachin', 'rahul', 'sachin', 'rahul', 'rahul', 'sachin', 'rahul',
       'sachin', 'rahul', 'rahul', 'rahul', 'rahul', 'sachin', 'rahul',
       'sachin', 'sachin', 'rahul', 'rahul', 'rahul', 'sachin', 'rahul',
       'sachin', 'sachin', 'sachin', 'sachin', 'rahul', 'sachin', 'rahul',
       'rahul', 'sachin', 'sachin', 'rahul', 'rahul', 'sachin', 'rahul',
       'rahul', 'sachin', 'rahul', 'rahul', 'rahul', 'rahul', 'rahul',
       'rahul', 'sachin', 'sachin', 'sachin', 'rahul', 'sachin', 'sachin',
       'sachin', 'sachin', 'sachin', 'sachin'

## **Problem 8**
<font color = 'Green'>**How many matches did Sachin take to score first 1000 runs, next 1000 runs, ...**

In [ ]:
sachin_cum_scores = np.cumsum(sachin)

In [ ]:
sachin_cum_scores

array([ 100.,  111.,  119.,  190.,  294.,  312.,  320.,  406.,  418.,
        503.,  521.,  525.,  532.,  569.,  583.,  583.,  587.,  587.,
        608.,  609.,  671.,  671.,  809.,  847.,  849.,  895.,  960.,
        960.,  999., 1047., 1188., 1250., 1262., 1263., 1304., 1315.,
       1318., 1504., 1515., 1542., 1569., 1620., 1638., 1670., 1816.,
       1821., 1866., 2007., 2019., 2084., 2111., 2118., 2134., 2136.,
       2164., 2170., 2293., 2413., 2420., 2423., 2423., 2504., 2506.,
       2560., 2682., 2686., 2700., 2700., 2800., 2815., 2815., 2872.,
       2971., 3008., 3046., 3078., 3099., 3131., 3171., 3171., 3176.,
       3184., 3189., 3189., 3239., 3269., 3306., 3395., 3399., 3497.,
       3580., 3673., 3673., 3725., 3877., 3878., 3886., 3979., 4024.,
       4050., 4050., 4051., 4051., 4067., 4114., 4203., 4206., 4207.,
       4260., 4276., 4276., 4357., 4371., 4449., 4455., 4560., 4682.,
       4691., 4699., 4727., 4762., 4831., 4844., 4941., 5034., 5036.,
       5072., 5111.,

In [ ]:
np.histogram(sachin_cum_scores, bins = np.arange(0, 10000, 1000))

(array([29, 18, 26, 25, 26, 26, 23, 22, 30], dtype=int32),
 array([   0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000]))